{
  lib,
  stdenv,
  sources,
  python3,
}:
stdenv.mkDerivation (_finalAttrs: {
  pname = "menubar-dock";
  version = lib.removePrefix "v" sources.menubar-dock.version;
  inherit (sources.menubar-dock) src;

  nativeBuildInputs = [python3];

  # Strip the build-fix script into the unpacked source so postPatch can run
  # it without needing Nix to embed it via a tricky heredoc.
  postUnpack = ''
    cp ${./strip-pods.py} $sourceRoot/strip-pods.py
    chmod +x $sourceRoot/strip-pods.py
  '';

  # The upstream project was authored for Xcode IDE only and requires a few
  # fixups to build from the CLI:
  # 1. Set DEVELOPER_DIR to full Xcode (CommandLineTools alone has no xcodebuild);
  #    xcode-select defaults to the CLT, so probe /Applications/Xcode.app and
  #    versioned /Applications/Xcode-*.app first. Mirrors `ccs-bar`'s approach
  #    of unsetting the apple-sdk's stale DEVELOPER_DIR/SDKROOT.
  # 2. Strip the CocoaPods integration: the Podfile declares zero pods, but
  #    the project still has `[CP] Check Pods Manifest.lock` build phases,
  #    `baseConfigurationReference = ...Pods-*.xcconfig`, and `Pods_*.framework`
  #    link references that all require `pod install` to satisfy. The script
  #    `strip-pods.py` (in the same directory) handles this and also replaces
  #    the broken shared scheme with one that targets `MenuBarDock`.
  # 3. Inject SUPPORTED_PLATFORMS = macosx; everywhere — the project predates
  #    Xcode 14+'s stricter scheme validation, which rejects schemes whose
  #    buildables have no supported platforms declared.
  postPatch = ''
    unset DEVELOPER_DIR SDKROOT

    find_xcode_developer_dir() {
      if [[ -x /Applications/Xcode.app/Contents/Developer/usr/bin/xcodebuild ]]; then
        echo /Applications/Xcode.app/Contents/Developer
        return 0
      fi
      for d in /Applications/Xcode-*/Contents/Developer; do
        if [[ -x "$d/usr/bin/xcodebuild" ]]; then
          echo "$d"
          return 0
        fi
      done
      return 1
    }

    if dev="$(find_xcode_developer_dir)"; then
      export DEVELOPER_DIR="$dev"
    else
      export DEVELOPER_DIR="$(/usr/bin/xcode-select -p)"
    fi

    if [[ ! -x "$DEVELOPER_DIR/usr/bin/xcodebuild" ]]; then
      echo "xcodebuild not found under '$DEVELOPER_DIR'." >&2
      echo "Install full Xcode (not just CommandLineTools) or set xcode-select." >&2
      exit 1
    fi

    python3 "$PWD/strip-pods.py" "$PWD/MenuBarDock.xcodeproj"
  '';

  # Build the MenuBarDock target via the synthetic scheme written by
  # strip-pods.py. The original shared scheme (`Menu Bar Dock.xcscheme`)
  # references "Menu Bar Dock" / "Menu Bar Dock.xcodeproj" — names that don't
  # match the actual target (`MenuBarDock`) or project (`MenuBarDock.xcodeproj`),
  # so Xcode 26 rejects it as "scheme not configured for the build action".
  #
  # We use `-derivedDataPath build` because Xcode's default DerivedData path
  # (`~/Library/Developer/Xcode/DerivedData/`) isn't writable in the nix
  # sandbox. `-derivedDataPath` requires `-scheme` (passing only `-target` is
  # rejected). The synthetic scheme generated by strip-pods.py targets the
  # MenuBarDock product by its real name.
  buildPhase = ''
    runHook preBuild

    arch="$(${stdenv.cc.targetPrefix}uname -m 2>/dev/null || uname -m)"
    case "$arch" in
      arm64|aarch64) host_arch=arm64 ;;
      *)             host_arch=x86_64 ;;
    esac

    /usr/bin/xcrun xcodebuild \
      -project MenuBarDock.xcodeproj \
      -scheme MenuBarDock \
      -configuration Release \
      -sdk macosx \
      -arch "$host_arch" \
      ONLY_ACTIVE_ARCH=NO \
      -derivedDataPath build \
      CODE_SIGN_IDENTITY="" \
      CODE_SIGNING_REQUIRED=NO \
      CODE_SIGNING_ALLOWED=NO \
      build

    runHook postBuild
  '';

  dontFixup = true;

  installPhase = ''
    runHook preInstall

    # xcodebuild with `-derivedDataPath build` writes the .app to
    # `build/Build/Products/Release/<Name>.app`.
    src="$PWD/build/Build/Products/Release/MenuBarDock.app"
    [ -d "$src" ] || { echo "expected build output not found: $src" >&2; exit 1; }

    dst="$out/Applications/MenuBarDock.app"
    mkdir -p "$(dirname "$dst")"
    cp -R "$src" "$dst"
  '';

  meta = {
    description = "macOS dock of running/pinned apps in the menu bar — fork with notification badges";
    homepage = "https://github.com/joaquinpiedracueva/menubar-dock";
    license = lib.licenses.mit;
    platforms = lib.platforms.darwin;
    maintainers = with lib.maintainers; [DivitMittal];
    sourceProvenance = with lib.sourceTypes; [fromSource];
  };
})
