local ipc = require("hs.ipc")
ipc.cliInstall("~/.local/bin")
ipc.cliSaveHistory(false)

hs.autoLaunch(true)
hs.dockIcon(false)
hs.menuIcon(true)
hs.preferencesDarkMode(true)
hs.uploadCrashData(false)
hs.automaticallyCheckForUpdates(false)