# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchurl,
  fetchFromGitHub,
}: {
  Iris = {
    pname = "Iris";
    version = "v0.2.1";
    src = fetchurl {
      url = "https://github.com/ahmetb/Iris/releases/download/v0.2.1/Iris-v0.2.1.zip";
      sha256 = "sha256-JZoKDwPCc0PXQpCyY8oe77XZymQ7NTMgWf0Kr+IE26o=";
    };
  };
  LibreScore = {
    pname = "LibreScore";
    version = "v6.0.23";
    src = fetchurl {
      url = "https://github.com/LibreScore/app-librescore/releases/download/v6.0.23/LibreScore.dmg";
      sha256 = "sha256-8/LqQL2dTsAYy3aIhzhlgw3BRIut6P0XduqucbPoB8Y=";
    };
  };
  LiveWallpaper = {
    pname = "LiveWallpaper";
    version = "V2.3";
    src = fetchurl {
      url = "https://github.com/thusvill/LiveWallpaperMacOS/releases/download/V2.3/LiveWallpaper.dmg";
      sha256 = "sha256-GW6tSVCrRo8Dx/s6gyRjsWC0dxFIw8J28GBSqrnfaIo=";
    };
  };
  LosslessSwitcher = {
    pname = "LosslessSwitcher";
    version = "2.0";
    src = fetchurl {
      url = "https://github.com/vincentneo/LosslessSwitcher/releases/download/2.0/LosslessSwitcher2.app.zip";
      sha256 = "sha256-vyzWG5r6GgyqekkbJcyyzBLwnbO5gxwNgUhUCD3Oroo=";
    };
  };
  MultiSoundChanger = {
    pname = "MultiSoundChanger";
    version = "1.0.1-BetterDisplay";
    src = fetchurl {
      url = "https://github.com/aonez/MultiSoundChanger/releases/download/1.0.1-BetterDisplay/MultiSoundChanger+BetterDisplay.zip";
      sha256 = "sha256-iY6V48247mNEgQ73QTZ5RJBsiNEji0bTVt8q43BIfJo=";
    };
  };
  SakuraWallpaper = {
    pname = "SakuraWallpaper";
    version = "1ec6c63f82e5826d7a2da529ebc40726357dd82c";
    src = fetchurl {
      url = "https://github.com/yueseqaz/SakuraWallpaper/releases/download/latest/SakuraWallpaper.dmg";
      sha256 = "sha256-dOJjMWY5OARLuo55Bv4R0vU9AK9LhO8HMNtL/DC473Q=";
    };
    date = "2026-05-21";
  };
  agevault = {
    pname = "agevault";
    version = "v1.1.1";
    src = fetchFromGitHub {
      owner = "ndavd";
      repo = "agevault";
      rev = "v1.1.1";
      fetchSubmodules = false;
      sha256 = "sha256-f7t/hzBfZi3OJtYPM4n5bDhm+LcceinDUZIpVsSSl/s=";
    };
  };
  cliclick = {
    pname = "cliclick";
    version = "5.1";
    src = fetchurl {
      url = "https://github.com/BlueM/cliclick/releases/download/5.1/cliclick.zip";
      sha256 = "sha256-cQkQ/S2t5qO1iJWUv8AZ59TCvu4J/Xd1A+ceqCrMkbw=";
    };
  };
  MacKernelSDK = {
    pname = "MacKernelSDK";
    version = "7af1933c27aefcbdf4809ee44478829aad30f9c1";
    src = fetchFromGitHub {
      owner = "acidanthera";
      repo = "MacKernelSDK";
      rev = "7af1933c27aefcbdf4809ee44478829aad30f9c1";
      fetchSubmodules = false;
      sha256 = "sha256-hnbBi5YA32B3Ts5Uk40CmRSaOvn76F80HCzzNM0DpzQ=";
    };
  };
  VoltageShift = {
    pname = "VoltageShift";
    version = "4fef84ffe10b7e79c4d6efa043e7873820590bd0";
    src = fetchFromGitHub {
      owner = "asepms92";
      repo = "VoltageShift";
      rev = "4fef84ffe10b7e79c4d6efa043e7873820590bd0";
      fetchSubmodules = false;
      sha256 = "sha256-GKWBEuuq/vPquGx4vYUI2uEf3uXEo+6uJrDVYnfYg3Q=";
    };
  };
  dmgwiz = {
    pname = "dmgwiz";
    version = "v1.1.0";
    src = fetchFromGitHub {
      owner = "citruz";
      repo = "dmgwiz";
      rev = "v1.1.0";
      fetchSubmodules = false;
      sha256 = "sha256-8iuucOOLKd9WoFEFwn5xP1ZZ2C1GAQeyVO6mSdDYb8Y=";
    };
  };
  get-apple-firmware = {
    pname = "get-apple-firmware";
    version = "68114441fb74a6985565feb5255b1037ca8d17e8";
    src = fetchurl {
      url = "https://raw.githubusercontent.com/t2linux/wiki/68114441fb74a6985565feb5255b1037ca8d17e8/docs/tools/firmware.sh";
      sha256 = "sha256-wcHYqiW7XwieRszQ2XOPwTv714T0maqSRGbGkPBZlh4=";
    };
  };
  libxls = {
    pname = "libxls";
    version = "1.6.3";
    src = fetchurl {
      url = "https://github.com/libxls/libxls/releases/download/v1.6.3/libxls-1.6.3.tar.gz";
      sha256 = "sha256-svuDbqC1JTo1L7XKVXQuKfBvlPlCHFuO7M7y5dQ/Yiw=";
    };
  };
  menubar-dock = {
    pname = "menubar-dock";
    version = "4.6";
    src = fetchurl {
      url = "https://github.com/EthanSK/Menu-Bar-Dock/releases/download/4.6/Menu.Bar.Dock.app.zip";
      sha256 = "sha256-bRV65XDf5CsvTZcse7sHE18KDHpOMnWPrUUoH9tcWl0=";
    };
  };
  option-analysis = {
    pname = "option-analysis";
    version = "eea826be99bec4ef9af98cb69778621c10e27a7d";
    src = fetchFromGitHub {
      owner = "harsh-vardhhan";
      repo = "option-analysis";
      rev = "eea826be99bec4ef9af98cb69778621c10e27a7d";
      fetchSubmodules = false;
      sha256 = "sha256-qz7fpJQAZrARJDU6OrxUTB6ExhjcbBGkQb8ir4jFdUI=";
    };
  };
  reapack-arm64 = {
    pname = "reapack-arm64";
    version = "1.2.6";
    src = fetchurl {
      url = "https://github.com/cfillion/reapack/releases/download/v1.2.6/reaper_reapack-arm64.dylib";
      sha256 = "sha256-x2cPOy5AW5A31JsZQaTYw3Yv/zJs7MDFisT67KFx8Hs=";
    };
  };
  reapack-x86_64 = {
    pname = "reapack-x86_64";
    version = "1.2.6";
    src = fetchurl {
      url = "https://github.com/cfillion/reapack/releases/download/v1.2.6/reaper_reapack-x86_64.dylib";
      sha256 = "sha256-SLJhl042ZxOEypAqOz1aYUF49Asb63wTjHQUEOpdfZ4=";
    };
  };
  reaper-sws-arm64 = {
    pname = "reaper-sws-arm64";
    version = "2.14.0.7";
    src = fetchurl {
      url = "https://github.com/reaper-oss/sws/releases/download/v2.14.0.7/reaper_sws-arm64.dylib";
      sha256 = "sha256-jmuob0qslYhxiE2ShfTwY4RJAKBLJSUb+VBEM0sQPbo=";
    };
  };
  reaper-sws-python32 = {
    pname = "reaper-sws-python32";
    version = "2.14.0.7";
    src = fetchurl {
      url = "https://github.com/reaper-oss/sws/releases/download/v2.14.0.7/sws_python32.py";
      sha256 = "sha256-np2r568csSdIS7VZHDASroZlXhpfxXwNn0gROTinWU4=";
    };
  };
  reaper-sws-python64 = {
    pname = "reaper-sws-python64";
    version = "2.14.0.7";
    src = fetchurl {
      url = "https://github.com/reaper-oss/sws/releases/download/v2.14.0.7/sws_python64.py";
      sha256 = "sha256-GDlvfARg1g5oTH2itEug6Auxr9iFlPDdGueInGmHqSI=";
    };
  };
  reaper-sws-x86_64 = {
    pname = "reaper-sws-x86_64";
    version = "2.14.0.7";
    src = fetchurl {
      url = "https://github.com/reaper-oss/sws/releases/download/v2.14.0.7/reaper_sws-x86_64.dylib";
      sha256 = "sha256-c0enRIXFN+dMDdxTQ3hFv0almTF0dfrSHILNigJp2Js=";
    };
  };
  spotify-player = {
    pname = "spotify-player";
    version = "v0.23.0";
    src = fetchFromGitHub {
      owner = "aome510";
      repo = "spotify-player";
      rev = "v0.23.0";
      fetchSubmodules = false;
      sha256 = "sha256-LjQGCE4xbD3+k78827u346/qhC6D8vrhyUq6c+8eWSw=";
    };
  };
  warpd = {
    pname = "warpd";
    version = "v2.2.0";
    src = fetchFromGitHub {
      owner = "atuan26";
      repo = "warpd";
      rev = "v2.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-ngWQdGKvHxng0C1LlmYHMWjcH4mzgrEFr6DvEa6LdUE=";
    };
  };
  zerobrew-zb-aarch64 = {
    pname = "zerobrew-zb-aarch64";
    version = "0.2.1";
    src = fetchurl {
      url = "https://github.com/lucasgelfond/zerobrew/releases/download/v0.2.1/zb-darwin-arm64";
      sha256 = "sha256-3ss9uE+XBI1VRVs0yppSolyIuJydfWL1nhMFALot8yM=";
    };
  };
  zerobrew-zb-x86_64 = {
    pname = "zerobrew-zb-x86_64";
    version = "0.2.1";
    src = fetchurl {
      url = "https://github.com/lucasgelfond/zerobrew/releases/download/v0.2.1/zb-darwin-x64";
      sha256 = "sha256-vGvJ4koxLCjGjuNI+0VVsQmJgh9cB1nu1zX5gB0SNow=";
    };
  };
  zerobrew-zbx-aarch64 = {
    pname = "zerobrew-zbx-aarch64";
    version = "0.2.1";
    src = fetchurl {
      url = "https://github.com/lucasgelfond/zerobrew/releases/download/v0.2.1/zbx-darwin-arm64";
      sha256 = "sha256-u5SxJz/8LxHPdIo4GUlHPGzeWwDTEo8XQ9TAsGryGXw=";
    };
  };
  zerobrew-zbx-x86_64 = {
    pname = "zerobrew-zbx-x86_64";
    version = "0.2.1";
    src = fetchurl {
      url = "https://github.com/lucasgelfond/zerobrew/releases/download/v0.2.1/zbx-darwin-x64";
      sha256 = "sha256-uge/oEFDRAACrO/ffCvIJJoBtcyMskJvtrniXKa9hAI=";
    };
  };
}
