# This file was generated by nvfetcher, please do not modify it manually.
{
  fetchurl,
  fetchFromGitHub,
}: {
  BetterDiscord = {
    pname = "BetterDiscord";
    version = "v1.3.0";
    src = fetchurl {
      url = "https://github.com/BetterDiscord/Installer/releases/download/v1.3.0/BetterDiscord-Mac.zip";
      sha256 = "sha256-hb3XtE+WJPd0CvTSZoLyFzDEemQ/3gCfKtdmr6GTVrg=";
    };
  };
  Hot = {
    pname = "Hot";
    version = "1.9.4";
    src = fetchurl {
      url = "https://github.com/macmade/Hot/releases/download/1.9.4/Hot.zip";
      sha256 = "sha256-5PbM92Bmc+5hGHC/sdTMi+hqUIBY24+btc9B6ZftYco=";
    };
  };
  Iris = {
    pname = "Iris";
    version = "v0.1.5";
    src = fetchurl {
      url = "https://github.com/ahmetb/Iris/releases/download/v0.1.5/Iris-v0.1.5.zip";
      sha256 = "sha256-ELFcvAi7QLdDy72CvrkfK+l2kmTSyIiZZ16OmwLpj+Y=";
    };
  };
  LibreScore = {
    pname = "LibreScore";
    version = "v6.0.22";
    src = fetchurl {
      url = "https://github.com/LibreScore/app-librescore/releases/download/v6.0.22/LibreScore.dmg";
      sha256 = "sha256-FVooTBCPaE8chR8YOjiQFi8L9G7anHICrufYDQjIh08=";
    };
  };
  LiveWallpaper = {
    pname = "LiveWallpaper";
    version = "V2.2";
    src = fetchurl {
      url = "https://github.com/thusvill/LiveWallpaperMacOS/releases/download/V2.2/LiveWallpaper.dmg";
      sha256 = "sha256-PU5UhPH2sk3aGT0RyR7ghNY8WLnzFSVdGC7CV2Q587k=";
    };
  };
  LosslessSwitcher = {
    pname = "LosslessSwitcher";
    version = "2.0";
    src = fetchurl {
      url = "https://github.com/vincentneo/LosslessSwitcher/releases/download/2.0/LosslessSwitcher2.app.zip";
      sha256 = "sha256-vyzWG5r6GgyqekkbJcyyzBLwnbO5gxwNgUhUCD3Oroo=";
    };
  };
  MultiSoundChanger = {
    pname = "MultiSoundChanger";
    version = "1.0.1-BetterDisplay";
    src = fetchurl {
      url = "https://github.com/aonez/MultiSoundChanger/releases/download/1.0.1-BetterDisplay/MultiSoundChanger+BetterDisplay.zip";
      sha256 = "sha256-iY6V48247mNEgQ73QTZ5RJBsiNEji0bTVt8q43BIfJo=";
    };
  };
  Pearcleaner = {
    pname = "Pearcleaner";
    version = "5.4.3";
    src = fetchurl {
      url = "https://github.com/alienator88/Pearcleaner/releases/download/5.4.3/Pearcleaner.zip";
      sha256 = "sha256-FtBGPb5wgrPE+FE493bBTk6ikuJbhrdv/gmvQwb7MLI=";
    };
  };
  SakuraWallpaper = {
    pname = "SakuraWallpaper";
    version = "v1.0.0";
    src = fetchFromGitHub {
      owner = "yueseqaz";
      repo = "SakuraWallpaper";
      rev = "v1.0.0";
      fetchSubmodules = false;
      sha256 = "sha256-9c6VnNNKByrsAjO38TYMlZOlHkk/ZxkzKLXrHBtpu58=";
    };
  };
  agevault = {
    pname = "agevault";
    version = "v1.1.1";
    src = fetchFromGitHub {
      owner = "ndavd";
      repo = "agevault";
      rev = "v1.1.1";
      fetchSubmodules = false;
      sha256 = "sha256-f7t/hzBfZi3OJtYPM4n5bDhm+LcceinDUZIpVsSSl/s=";
    };
  };
  cliclick = {
    pname = "cliclick";
    version = "5.1";
    src = fetchurl {
      url = "https://github.com/BlueM/cliclick/releases/download/5.1/cliclick.zip";
      sha256 = "sha256-cQkQ/S2t5qO1iJWUv8AZ59TCvu4J/Xd1A+ceqCrMkbw=";
    };
  };
  dmgwiz = {
    pname = "dmgwiz";
    version = "v1.1.0";
    src = fetchFromGitHub {
      owner = "citruz";
      repo = "dmgwiz";
      rev = "v1.1.0";
      fetchSubmodules = false;
      sha256 = "sha256-8iuucOOLKd9WoFEFwn5xP1ZZ2C1GAQeyVO6mSdDYb8Y=";
    };
  };
  libxls = {
    pname = "libxls";
    version = "1.6.3";
    src = fetchurl {
      url = "https://github.com/libxls/libxls/releases/download/v1.6.3/libxls-1.6.3.tar.gz";
      sha256 = "sha256-svuDbqC1JTo1L7XKVXQuKfBvlPlCHFuO7M7y5dQ/Yiw=";
    };
  };
  menubar-dock = {
    pname = "menubar-dock";
    version = "4.6";
    src = fetchurl {
      url = "https://github.com/EthanSK/Menu-Bar-Dock/releases/download/4.6/Menu.Bar.Dock.app.zip";
      sha256 = "sha256-bRV65XDf5CsvTZcse7sHE18KDHpOMnWPrUUoH9tcWl0=";
    };
  };
  mole = {
    pname = "mole";
    version = "V1.33.0";
    src = fetchFromGitHub {
      owner = "tw93";
      repo = "Mole";
      rev = "V1.33.0";
      fetchSubmodules = false;
      sha256 = "sha256-IQcnwpwzabRLznqSin73OI7G7Jw1OjXX2JBIPFkquas=";
    };
  };
  nomacs = {
    pname = "nomacs";
    version = "3.22.0";
    src = fetchurl {
      url = "https://github.com/nomacs/nomacs/releases/download/3.22.0/nomacs-3.22.0-macOS-x86_64.zip";
      sha256 = "sha256-iKNLHdkgtdP2bdpGbwVXEvmXtODA7OT7Go/2DWhWGo0=";
    };
  };
  reapack-arm64 = {
    pname = "reapack-arm64";
    version = "1.2.6";
    src = fetchurl {
      url = "https://github.com/cfillion/reapack/releases/download/v1.2.6/reaper_reapack-arm64.dylib";
      sha256 = "sha256-x2cPOy5AW5A31JsZQaTYw3Yv/zJs7MDFisT67KFx8Hs=";
    };
  };
  reapack-x86_64 = {
    pname = "reapack-x86_64";
    version = "1.2.6";
    src = fetchurl {
      url = "https://github.com/cfillion/reapack/releases/download/v1.2.6/reaper_reapack-x86_64.dylib";
      sha256 = "sha256-SLJhl042ZxOEypAqOz1aYUF49Asb63wTjHQUEOpdfZ4=";
    };
  };
  reaper-sws-arm64 = {
    pname = "reaper-sws-arm64";
    version = "2.14.0.7";
    src = fetchurl {
      url = "https://github.com/reaper-oss/sws/releases/download/v2.14.0.7/reaper_sws-arm64.dylib";
      sha256 = "sha256-jmuob0qslYhxiE2ShfTwY4RJAKBLJSUb+VBEM0sQPbo=";
    };
  };
  reaper-sws-python32 = {
    pname = "reaper-sws-python32";
    version = "2.14.0.7";
    src = fetchurl {
      url = "https://github.com/reaper-oss/sws/releases/download/v2.14.0.7/sws_python32.py";
      sha256 = "sha256-np2r568csSdIS7VZHDASroZlXhpfxXwNn0gROTinWU4=";
    };
  };
  reaper-sws-python64 = {
    pname = "reaper-sws-python64";
    version = "2.14.0.7";
    src = fetchurl {
      url = "https://github.com/reaper-oss/sws/releases/download/v2.14.0.7/sws_python64.py";
      sha256 = "sha256-GDlvfARg1g5oTH2itEug6Auxr9iFlPDdGueInGmHqSI=";
    };
  };
  reaper-sws-x86_64 = {
    pname = "reaper-sws-x86_64";
    version = "2.14.0.7";
    src = fetchurl {
      url = "https://github.com/reaper-oss/sws/releases/download/v2.14.0.7/reaper_sws-x86_64.dylib";
      sha256 = "sha256-c0enRIXFN+dMDdxTQ3hFv0almTF0dfrSHILNigJp2Js=";
    };
  };
  spotify-player = {
    pname = "spotify-player";
    version = "v0.23.0";
    src = fetchFromGitHub {
      owner = "aome510";
      repo = "spotify-player";
      rev = "v0.23.0";
      fetchSubmodules = false;
      sha256 = "sha256-LjQGCE4xbD3+k78827u346/qhC6D8vrhyUq6c+8eWSw=";
    };
  };
  unxip = {
    pname = "unxip";
    version = "v3.3";
    src = fetchurl {
      url = "https://github.com/saagarjha/unxip/releases/download/v3.3/unxip";
      sha256 = "sha256-R12///1w4GcV+Wa4eI+N02dy8zCzNg/272/x/M0vFP4=";
    };
  };
  warpd = {
    pname = "warpd";
    version = "v2.2.0";
    src = fetchFromGitHub {
      owner = "atuan26";
      repo = "warpd";
      rev = "v2.2.0";
      fetchSubmodules = false;
      sha256 = "sha256-ngWQdGKvHxng0C1LlmYHMWjcH4mzgrEFr6DvEa6LdUE=";
    };
  };
  zerobrew-zb-aarch64 = {
    pname = "zerobrew-zb-aarch64";
    version = "0.2.1";
    src = fetchurl {
      url = "https://github.com/lucasgelfond/zerobrew/releases/download/v0.2.1/zb-darwin-arm64";
      sha256 = "sha256-3ss9uE+XBI1VRVs0yppSolyIuJydfWL1nhMFALot8yM=";
    };
  };
  zerobrew-zb-x86_64 = {
    pname = "zerobrew-zb-x86_64";
    version = "0.2.1";
    src = fetchurl {
      url = "https://github.com/lucasgelfond/zerobrew/releases/download/v0.2.1/zb-darwin-x64";
      sha256 = "sha256-vGvJ4koxLCjGjuNI+0VVsQmJgh9cB1nu1zX5gB0SNow=";
    };
  };
  zerobrew-zbx-aarch64 = {
    pname = "zerobrew-zbx-aarch64";
    version = "0.2.1";
    src = fetchurl {
      url = "https://github.com/lucasgelfond/zerobrew/releases/download/v0.2.1/zbx-darwin-arm64";
      sha256 = "sha256-u5SxJz/8LxHPdIo4GUlHPGzeWwDTEo8XQ9TAsGryGXw=";
    };
  };
  zerobrew-zbx-x86_64 = {
    pname = "zerobrew-zbx-x86_64";
    version = "0.2.1";
    src = fetchurl {
      url = "https://github.com/lucasgelfond/zerobrew/releases/download/v0.2.1/zbx-darwin-x64";
      sha256 = "sha256-uge/oEFDRAACrO/ffCvIJJoBtcyMskJvtrniXKa9hAI=";
    };
  };
}
