name: build-darwin-hosts

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [master]
    paths-ignore:
      - "**/*.md"
      - ".github/**"
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build-L1-job:
    name: "Builds L1 darwin configuration"

    runs-on: macos-latest
    environment:
      name: dev
    permissions:
      contents: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@main
        with:
          fetch-depth: 1

      - name: "Installing nix"
        uses: DeterminateSystems/nix-installer-action@main

      - uses: cachix/cachix-action@master
        with:
          name: divitmittal
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: Building L1 nix-darwin config
        run: nix build --accept-flake-config .#darwinConfigurations.L1.config.system.build.toplevel