name: Run flake checks

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [master]
    paths-ignore:
      - "**/*.md"
      - ".github/**"
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  check-job:
    name: Run `nix flake check`

    runs-on: ubuntu-latest
    environment:
      name: dev
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@main
        with:
          fetch-depth: 1

      - name: Set env var
        run: export OS_NIXCFG=$(pwd)

      - name: Installing Nix
        uses: DeterminateSystems/nix-installer-action@main
        with:
          extra-conf: |
            extra-experimental-features = pipe-operators

      - name: Configure to use personal binary cache @ Cachix
        uses: cachix/cachix-action@master
        with:
          name: divitmittal
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: SSH-agent with auth for private repos
        uses: webfactory/ssh-agent@master
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Check flake
        run: nix flake check --impure --all-systems
