jobs:
  build-nixos-configuration:
    environment:
      name: dev
    permissions:
      contents: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@main
      with:
        fetch-depth: 1
    - name: Set env var
      run: echo "OS_NIXCFG=$(pwd)" >> "$GITHUB_ENV"
    - uses: DeterminateSystems/nix-installer-action@v17
    - name: Configure to use personal binary cache @ Cachix
      uses: cachix/cachix-action@master
      with:
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
        name: divitmittal
    - name: SSH-agent with auth for private repos
      uses: webfactory/ssh-agent@master
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Builds a nixos configuration
      run: nix build --accept-flake-config .#nixosConfigurations.WSL.config.system.build.toplevel
        --impure --show-trace
    timeout-minutes: 30
'on':
  pull_request:
    branches:
    - master
  push:
    branches:
    - master
    paths-ignore:
    - '**/*.md'
    - .github/**
  workflow_dispatch: {}
