name: Darwin Configuration Build

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

on:
  push:
    branches: [master]
    paths-ignore:
      - "**/*.md"
      - ".github/**"
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  build-L1-job:
    name: Builds a nixos configuration

    runs-on: ubuntu-latest
    environment:
      name: dev
    permissions:
      contents: write

    steps:
      - name: Checkout repo
        uses: actions/checkout@main
        with:
          fetch-depth: 1

      - name: Set env var
        run: echo "OS_NIXCFG=$(pwd)" >> "$GITHUB_ENV"

      - name: Installing Nix
        uses: DeterminateSystems/nix-installer-action@main

      - name: Configure to use personal binary cache @ Cachix
        uses: cachix/cachix-action@master
        with:
          name: divitmittal
          authToken: "${{ secrets.CACHIX_AUTH_TOKEN }}"

      - name: SSH-agent with auth for private repos
        uses: webfactory/ssh-agent@master
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Building a nixos configuration
        run: nix build --accept-flake-config .#nixosConfigurations.WSL.config.system.build.toplevel --impure --show-trace