jobs:
  build-nixos-configuration:
    environment:
      name: dev
    permissions:
      contents: write
      id-token: write
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@main
      with:
        fetch-depth: 1
    - name: Set env var
      run: echo "OS_NIXCFG=$(pwd)" 1>> "$GITHUB_ENV"
    - uses: DeterminateSystems/nix-installer-action@v19
    - name: Magic Nix Cache(Use Github Actions Cache)
      uses: DeterminateSystems/magic-nix-cache-action@main
    - name: Configure to use personal binary cache @ Cachix
      uses: cachix/cachix-action@master
      with:
        authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
        name: divitmittal
    - name: SSH-agent with auth for private repos
      uses: webfactory/ssh-agent@master
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Builds a nixos configuration
      run: nix -vL build --accept-flake-config .#nixosConfigurations.WSL.config.system.build.toplevel
        --impure --show-trace
    timeout-minutes: 90
'on':
  pull_request:
    branches:
    - master
    paths-ignore:
    - '**/*.md'
    - '**/*.adoc'
    - '**/*.jpeg'
    - '**/*.jpg'
    - '**/*.png'
    - '**/*.svg'
    - .github/**
    - .git*
    - assets/**
    - common/home/**
    - common/hosts/droid/**
    - common/hosts/darwin/**
    - home/**
    - hosts/droid/**
    - hosts/darwin/**
    - modules/home/**
    - modules/hosts/droid/**
    - modules/hosts/darwin/**
  push:
    branches:
    - master
    paths-ignore:
    - '**/*.md'
    - '**/*.adoc'
    - '**/*.jpeg'
    - '**/*.jpg'
    - '**/*.png'
    - '**/*.svg'
    - .github/**
    - .git*
    - assets/**
    - common/home/**
    - common/hosts/droid/**
    - common/hosts/darwin/**
    - home/**
    - hosts/droid/**
    - hosts/darwin/**
    - modules/home/**
    - modules/hosts/droid/**
    - modules/hosts/darwin/**
  workflow_dispatch: {}
